-- AGREEGATION FUNCTIONS

SELECT * FROM sales ORDER BY NAME, sale DESC;
SELECT DISTINCT city FROM sales;
SELECT * FROM sales WHERE NAME LIKE "%landio";
SELECT * FROM sales WHERE MONTH IN ('out','nov') ORDER BY MONTH;
SELECT * FROM sales WHERE sale > 3000 AND sale < 4000 ORDER BY sale;
SELECT * FROM sales WHERE sale BETWEEN 300 AND 400 ORDER BY sale;